CodeMirror bump to 6.0
scalacenter/scastie pull request #628
Opened 2022-08-30 14:36 UTC by rochala

This PR is very big as the API between CodeMirror5 and CodeMirror6 has completely changed.
I also bumped other libraries, especially react to version 17+ as it provides big simplification with introduced Hooks.

I managed to port almost all features ( at least all that I have found ).

As for remaining things to do:
- Rewrite theming,
- Rewrite css,
- Rewrite remaining components into react hooks

For all of those tasks I'll create corresponding issues.

2022-08-31 10:31 UTC, rochala commented
The CI is failing due to our configuration. We are always fetching latest MongoDB and to a surprise there was a new major release between last CI run. MongoDB no longer supports some operations and this will require changing our client driver. I'll do this in separate PR to fix the CI and then pull it here.

2022-09-01 16:05 UTC, sjrd requested changes
Overall LGTM. I spotted a few suspicious or improvable things here and there.

2022-09-01 16:05 UTC, sjrd commented on client/src/main/scala/com.olegych.scastie.client/components/editor/OnChangeHandler.scala
> +  override def propertyIsEnumerable(v: PropertyKey): Boolean = false
This is suspicious. It seems that these lines try and annihilate built-in methods in JavaScript's `Object`. What's the rationale here?

2022-09-01 16:05 UTC, sjrd commented on client/webpack/webpack-prod.config.js
> +             // "resolve-url-loader"
Any reason to preserve those comments, and the ones below?

2022-09-05 11:55 UTC, rochala commented on client/webpack/webpack-prod.config.js
> +             // "resolve-url-loader"
No, these are leftovers after webpack fix.

2022-09-05 11:55 UTC, rochala commented on client/src/main/scala/com.olegych.scastie.client/components/editor/OnChangeHandler.scala
> +  override def propertyIsEnumerable(v: PropertyKey): Boolean = false
I extended PluginValue instead of an object and it required me to do so. It's changed now.

2022-09-05 11:55 UTC, rochala commented on client/src/main/scala/com.olegych.scastie.client/components/SideBar.scala
> +@JSImport("resources/images/icon-scastie.png", JSImport.Default)
I got such error `Uncaught org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: [object Module] is not an instance of java.lang.String`

2022-09-05 12:09 UTC, rochala commented on client/src/main/scala/com.olegych.scastie.client/ScastieState.scala
> +    copyAndSave(outputs = outputs.copy(instrumentations = instrumentations))
This method is not necessary at all.

2022-09-14 06:35 UTC, vincenzobaz approved these changes
Not easy to review such a large PR.
It looks good and it is awesome to see so many small improvements!

2022-09-22 14:31 UTC, rochala commented on client/src/main/scala/com.olegych.scastie.client/components/TargetSelector.scala
> +      .withHooks[TargetSelector]
There are further changes to be made to make all components with hooks, but it's not the priority right now

2022-09-23 08:44 UTC, sjrd commented
I see there's a Merge commit from `main` in this PR. This creates very weird histories. In general, we prefer to rebase PR branches on top of `main` (possibly squashing things) so that the history makes better sense. Would you mind rebasing everything?

2022-09-23 08:49 UTC, sjrd commented
Other than rebasing, LGTM.

2022-09-23 10:54 UTC, merged