Metals support
scalacenter/scastie pull request #655
Opened 2022-11-07 14:31 UTC by rochala

This is PR which adds metals support for Scastie.

Currently supported IDE features are: `autocompletion` and `hover`.
It should be straightforward to add further features like `go to definition` or signature help.

Metals runner is a http4s server which is responsible for providing interactive features to the IDE.
It is responsible for many things starting from managing the lifetime of `PresentationCompiler` instances to downloading and creating classpath for correct responses.

I know that this PR is very big, but I cannot think how can I split it into smaller parts.
If you want any information during code review feel free to setup a call with me.

Fixes https://github.com/scalacenter/scastie/issues/517

2022-11-08 17:46 UTC, julienrf requested changes
This looks very promising, thank you Jędrzej for all this work!

I have some general remarks, and some specific comments (see below).

- Why does metals-server need to run as a separate server than the scastie server?
- Could you please update the documentation explaining how to run everything locally (if needed)?
- Could you also add comments/documentation explaining the purpose of every added class/object? (think about the next maintainers :wink:)

2022-11-08 17:46 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/ScastieMetals.scala
> +trait ScastieMetals[F[_]]:
Do we leverage somewhere the fact that this type is generic over `F[_]`? If not, I would recommend making it concrete (replace it with `IO`), unless `IO` is too low-level?

2022-11-08 17:46 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/MetalsDispatcher.scala
> +      .fetch()
It looks like this is performing a side-effect but it is not returning an `F[_]`. Is this a problem? Should it be wrapped?

2022-11-08 17:46 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/PresentationCompilers.scala
> +      // NOTE(olafur): ServiceLoader doesn't find the service on Appveyor for
Where does this comment come from?

2022-11-08 17:46 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/DTOCodecs.scala
> +object DTOCodecs {
We could also define the HTTP endpoints (not just the schemas of JSON entities), to avoid maintaining them on both the client and server sides.

2022-11-08 17:46 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/ScastiePresentationCompiler.scala
> +    Async[F].fromFuture(pc.complete(offsetParams.toOffsetParams).asScala.pure)
I am not familiar with cats-effect, but `fromFuture(someComputation().pure)` sounds wrong to me. The call to `pc.complete` should be delayed. Maybe `suspend` is the right thing to do instead of `pure`?

2022-11-08 17:46 UTC, julienrf commented on project/DockerHelper.scala
> +      from("eclipse-temurin:17")
I am not sure about this change. I think alpine was chosen because it is small. What is the size of the image when you use `eclipse-temurin`?

2022-11-08 18:16 UTC, tgodzik reviewed
Great work @rochala ! I added some comments from metals perspective, just took a quick look though, so let me know if there is anything I should review in depth.

2022-11-08 18:16 UTC, tgodzik commented on metals-runner/src/main/scala/scastie/metals/ScastieSymbolSearch.scala
> +    ju.Collections.emptyList()
Could we use `OnDemandSymbolIndex` here? This method is used for the presentation compiler if soemthing is located in source jars. Or is there no possibility to show source jars within scastie?

2022-11-08 18:16 UTC, tgodzik commented on metals-runner/src/main/scala/scastie/metals/MetalsDispatcher.scala
> +      case Typelevel(scalaVersion)                  => Set.empty
I don't think typelevel is still needed, the fork is discontinued.

2022-11-08 18:16 UTC, tgodzik commented on metals-runner/src/main/scala/scastie/metals/DTOCodecs.scala
> +          case "Typelevel" => Right(ScalaTarget.Typelevel(scalaVersion))
This shouldn't be needed anymore

2022-11-10 13:56 UTC, rochala commented on api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala
> -          "2.10.6"
This is leftover from my changes. I had to change build server to sbt and it could not resolve semantic_db for this version. It will be reverted.

2022-11-10 13:56 UTC, rochala commented on CONTRIBUTING.md
> +./metalsRunner.sh
The reason behind two commands is that those are 2 separate processes. I think it may be better to have them separated into 2 scripts, so in case any of them fails during runtime we can restart only one of them. This also will be addressed in the future if I manage to migrate whole Scastie to docker images to simplify deployment.
Also you have to run this manually only for local deployment ( which I cannot fully test because of arm64 )

2022-11-10 13:57 UTC, rochala commented on metals-runner/src/main/scala/scastie/metals/DTOCodecs.scala
> +object DTOCodecs {
I think this can be added as a future improvement. Right now we only have 4 endpoints and I don't see how can it help with inconsistency between play and crice. I already have separate branch which unifies them.

2022-11-10 13:57 UTC, rochala commented on build.sbt
> +      "com.google.guava" % "guava" % "31.1-jre"
I think there are no Java converters used for Guava. Most of the cases was to handle LSP4J output.

2022-11-10 13:58 UTC, rochala commented on metals-runner/src/main/scala/scastie/metals/ScastiePresentationCompiler.scala
> +    Async[F].fromFuture(pc.complete(offsetParams.toOffsetParams).asScala.pure)
I agree, `delayed` was the proper way to create it.

2022-11-10 13:59 UTC, rochala commented on project/DockerHelper.scala
> +      from("eclipse-temurin:17")
This is also leftover from my efforts to fix building images on m1 processors. Alpine images with java are not published and ready for arm64 so I changed it to make it work on my setup. I can revert this for now and we can talk about this when docker will be fixed in Scastie.

2022-11-10 13:59 UTC, rochala commented on metals-runner/src/main/scala/scastie/metals/ScastieSymbolSearch.scala
> +    ju.Collections.emptyList()
It's not possible for the moment. It is planned to be added in next PR's along with signatureHelp and other capabilities but for now I want to merge auto-completion and hover as a base for further extensions.

2022-11-10 13:59 UTC, rochala commented on metals-runner/src/main/scala/scastie/metals/DTOCodecs.scala
> +          case "Typelevel" => Right(ScalaTarget.Typelevel(scalaVersion))
It is only to support backward compatibility so we don't get parsing error but more detailed one.

2022-11-10 13:59 UTC, rochala commented on metals-runner/src/main/scala/scastie/metals/MetalsDispatcher.scala
> +      case Typelevel(scalaVersion)                  => Set.empty
This is left for old snippets compatibility. I fixed it so proper sources are always downloaded for it but if we are to change it, I think it should also be discussed and put in separate PR.

2022-11-10 14:03 UTC, rochala commented
Why does metals-server need to run as a separate server than the scastie server?
- These are 2 separated jvm processes. I wanted to separate them so in case of failure we will only lose metals.

Could you please update the documentation explaining how to run everything locally (if needed)?
- Nothing changed on that part. It is still `startAll` in sbt and  `yarn dev` in your shell for dev and startAllProd for prod

Could you also add comments/documentation explaining the purpose of every added class/object? (think about the next maintainers 😉)
- I added them to the most complex places.

2022-11-14 09:53 UTC, julienrf requested changes
Thank you @rochala!

This looks great to me except the way to set up an exclusive lock, see my comment below.

2022-11-14 09:53 UTC, julienrf commented on client/src/main/scala/com.olegych.scastie.client/components/ShareButton.scala
> +class ShareButton {
I think this is unintended :)

2022-11-14 09:53 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/PresentationCompilers.scala
> +    def load[T](cls: Class[T], className: String, classloader: URLClassLoader): F[T] = Sync[F].blocking {
I might be wrong but it looks to me that what you want to achieve here is to protect the method `load` from being executed on multiple threads at the same time. This is not what `blocking` does. As far as I understand, `blocking` informs the surrounding execution context that the code block may block the current thread so that the surrounding execution context may provide additional threads to avoid thread starvation.

To properly protect against concurrent execution on multiple threads, you should use [synchronized](https://www.scala-lang.org/api/current/scala/AnyRef.html#synchronized[T0](x$1:=%3ET0):T0).

2022-11-22 14:14 UTC, julienrf commented on metals-runner/src/main/scala/scastie/metals/Server.scala
> +          .withPort(port"8000")
I guess the port number does not need to be configurable since we run it through Docker and we can remap it as we want?

2022-11-22 14:14 UTC, julienrf commented on project/plugins.sbt
> +addSbtPlugin("com.evolution" % "sbt-artifactory-plugin" % "0.0.2")
Do we use it?

2022-11-22 14:14 UTC, julienrf approved these changes
Thank you @rochala, that looks good to me besides the minor comments I left!

2022-11-22 14:16 UTC, rochala commented on project/plugins.sbt
> +addSbtPlugin("com.evolution" % "sbt-artifactory-plugin" % "0.0.2")
This is required for scache dependency resolving as they are not publishing on ivy nor maven central

2022-11-22 14:51 UTC, merged

2023-01-17 08:17 UTC, stefanobaghino commented
I just saw this on the main deployment. I constantly use Scastie to show people snippets of code on StackOverflow and this things makes it so much easier for me to use it, in particular autocompletion. Thanks for implementing this!