Fix embedded UI and CSS polution
scalacenter/scastie pull request #687
Opened 2023-01-02 18:27 UTC by rochala

fixes #681 

New revamped embedded UI which is not overlapping with the code.
Also, embedded css shouldn't pollute local css after this changes.

![image](https://user-images.githubusercontent.com/48657087/210264734-e02f9a4f-8836-443c-bc85-2a8dd076a1ab.png)

2023-01-02 23:10 UTC, leobenkel requested changes
Careful to remove the `.DS_Store` file and to add it to `.gitignore`.

2023-01-03 09:01 UTC, julienrf commented on client/src/main/resources/sass/embed.scss
> +  @include reset();
It is not clear to me how this is working. The `reset` mix-in defines rules that apply to global elements such as `<html>`. Are those rules still going to be applied when the mix-in is called from here?

2023-01-03 09:05 UTC, rochala commented on client/src/main/resources/sass/embed.scss
> +  @include reset();
When mixin is run inside tag, it will be in its scope so:
- .scastie body h1 ...

This allows us to have top-level reset on main scastie website, while isolating it in embedded css.
The proper solution to this would be to reset elements only inside the editor "decorations", and not use it at all on our website. All css rules should be properly assigned to tags and classes and explicitly remove default ones, but this is too much effort to do it right now.

2023-01-03 09:08 UTC, julienrf commented on client/src/main/resources/sass/embed.scss
> +  @include reset();
> .scastie body

But I guess that rule will never be applied? I understand that that’s what we want in some sense because we don’t want to change the style of the host website, but I wonder if that can have bad consequences too in case the styling of scastie did rely on some of those global rules to be applied.

2023-01-03 09:16 UTC, rochala commented on client/src/main/resources/sass/embed.scss
> +  @include reset();
Ideally they should be applied only to .editor-wrapper, but whole website is build with this css rules as a global tag.
Removing it broke the website and fixing it would basically require rewriting whole css.

This is what happens without it as tag has default css:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/48657087/210328077-96abf4cb-0102-452b-a1f9-3506940be4a2.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/48657087/210328146-8cee2405-21e6-4f0a-9877-2c07f3193d80.png">

2023-01-03 09:18 UTC, julienrf approved these changes
Please remove the `.DS_Store` file (and add it to your local .gitignore file)

2023-01-05 10:34 UTC, merged