Add support for Scala-CLI
scalacenter/scastie pull request #919
Opened 2023-08-03 13:41 UTC by Maeeen

# Description

This PR is about adding a support for Scala-CLI inside Scastie. This has been requested on issue #603.

## Detailed changes…

### … on the Scala-CLI runner

This PR introduces a new SBT subproject, namely `scliRunner`. It proceeds similarly to the `sbtRunner` except that it communicates with Scala-CLI using the [BSP protocol](https://build-server-protocol.github.io/) (with the [`ch.epfl.bsp4j`](https://mvnrepository.com/artifact/ch.epfl.scala/bsp4j) library). Scala-CLI needs to be properly installed on the host machine for it to work.

Note on abuses: to prevent any, a timeout had to be properly set-up for the compilation and running the snippets. In case of non-finishing compilations, the runner will simply `sys.exit(-1)` and Docker will restart the container (it is assumed that this will not happen oftenly). For non-finishing executions, Scala-CLI refused during testing to cancel run requests (i.e. cancel the program): to prevent this, the runner will execute Java on its own.

Note on instrumentation: the code is instrumented without the directives ; directives are prepended at the top of the file with the instrumented code.

### … on the cross-compiled API

Now, a new `ScalaTarget` is defined and is only for Scala-CLI. Also, ping/pongs messages between the dispatchers and the runners have been renamed to a more general name.

### … on the Metals runner

The Metals runner will parse the directives using the [using_directives](https://github.com/VirtusLab/using_directives) library. Client sends a `/isConfigurationSupported` with the configuration (with the code) and the Metals runner will send the configuration to use for subsequent requests. The runner will solve dependencies, find the Scala version and return the correct configuration. The client will simply pretend to be using SBT afterwards.

### … on the load balancer part

Now, the `DispatchActor` handles all the business stuff (saving snippets, etc.) : it will forward the SBT and Scala-CLI run requests to two distinct actors: `ScliDispatcher` and `SbtDispatcher`

### … on the client

The user can chose Scala-CLI as a target and also convert snippets from SBT to Scala-CLI!
Also, if the directives are modified, after ~5 seconds, it will show a "Reload metals" button to actually reload metals with all the directives.

### … what misses?

The deployment script actually is not made yet. But I prefer making a PR about the implementation to avoid a too huge PR.

## Closes

This PR closes #603.

## Note

This is my first PR to an OSS. Any suggestions about anything is kindly appreciated.

2023-08-11 06:38 UTC, rochala requested changes
I did a first part of code review. I'll do another one when you address current issues and CI will pass. There are few issues, that we must fix but other than that great job and thanks for your work !

2023-08-11 06:38 UTC, rochala commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/BspClient.scala
> +      .map(_.getTargets().stream().filter(t => {
Don't work on java streams, instead convert it to Scala. If you could change it.

2023-08-11 06:38 UTC, rochala commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/BspClient.scala
> +        sys.exit(-1)
add comment while we're doing this

2023-08-11 06:38 UTC, rochala commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/BspClient.scala
> +    val process = Process(
add FIXME and explain what needs to be done to not start process manually but rather rely on scala-cli / bloop to run it.

2023-08-11 06:38 UTC, rochala commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/ScliMain.scala
> +    val isProduction = true
not always true

2023-08-11 06:38 UTC, rochala commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/ScliRunner.scala
> +  private val javaProcesses = TrieMap[SnippetId, Process]() // mutable and concurrent HashMap
Is there ever more than 1 process tho ?

2023-08-11 21:42 UTC, Maeeen commented on api/src/main/scala/com.olegych.scastie.api/ApiModels.scala
> +case class ScastieMetalsOptions(dependencies: Set[ScalaDependency], scalaTarget: ScalaTarget, code: Option[String] = Some(""))
It can be made to None, and it will be!

2023-08-11 21:48 UTC, Maeeen commented on api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala
> +
That's not actually how it handles the Scala version.
```scala
    // case of > using scala 3…
    if (version.startsWith("3")) {
      if (version == "3") // if it is exactly > using scala 3
        Some(ScalaTarget.Scala3(BuildInfo.latest3))
      else // if it is > using scala 3.x.x
        Some(ScalaTarget.Scala3(version))
```

But now that we actually talk about it, I thought that the format 3.x is illegal. Is it the case?

2023-08-13 17:04 UTC, rochala commented on api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala
> +
Oh I didnt' notice. So is there any reason we are using the latest version for 2.13, 2.12 etc ? I think we shouldn't use latest version for example what will happen if user sets 2.13.10 and wants to show something specific to this version ?

2023-08-15 12:05 UTC, Maeeen commented on scli-runner/src/main/scala/com.olegych.scastie.sclirunner/ScliRunner.scala
> +  private val javaProcesses = TrieMap[SnippetId, Process]() // mutable and concurrent HashMap
Yes, indeed. I was thinking it was maybe possible to make parallel runs when I wrote the code but I think it's a better idea to just not do it. Thanks for the catch!

2023-08-15 16:30 UTC, Maeeen commented on client/src/main/scala/com.olegych.scastie.client/scli/ScalaCliUtils.scala
> +    } else if (target.targetType == ScalaTargetType.ScalaCli) {
I've tried changing it into the following:
```scala
  def convertInputsToScalaCli(in: Inputs): Either[Inputs, String] = {
    in match {
      case Inputs(_, _, _, _, _, sbtConfigExtra, _, _, _, _, _) if !sbtConfigExtra.isEmpty() && sbtConfigExtra != Inputs.default.sbtConfigExtra =>
        Right("Custom SBT config is not supported in Scala-CLI")

      case Inputs(_, _, target, _, _, _, _, _, _, _, _) if target.targetType == ScalaTargetType.ScalaCli => 
        Right("Already a Scala-CLI snippet.")

      case Inputs(_isWorksheetMode, code, target, libraries, _, _, _, _, _, _, _) if target.targetType == ScalaTargetType.Scala2 || target.targetType == ScalaTargetType.Scala3 =>
        Left(
          Inputs.default.copy(_isWorksheetMode = _isWorksheetMode,
              code = prependWithDirectives(target.scalaVersion, libraries, code),
              target = ScalaTarget.ScalaCli()
          )
        )

      case Inputs(_, _, target, _, _, _, _, _, _, _, _) => Right(s"Unsupported target: ${target.targetType}")

      case _ => Right("Can not convert to Scala-CLI.")
    }
  }
```
It does not seem to be that much of an improvement in my opinion, just different ways of writing it.

2023-08-15 16:32 UTC, Maeeen commented
I'll make all the changes and let you know when it is ready!

2023-12-20 10:01 UTC, rochala commented
Had to rebase. Because of that closing this in favor of https://github.com/scalacenter/scastie/pull/997

2023-12-20 10:01 UTC, closed without merging